### ISSUE TITLE
Automatically set "security.protocol" property to "SSL" if "ssl" property is set

### ISSUE THREAD

**Issue by Woodz** [spring-projects/spring-integration-kafka#294]
I believe that in all scenarios where SpringBoot autoconfig for Kafka has "ssl" property set, "security.protocol" should be set to "SSL". Therefore, to avoid confusion (e.g. #157) and to minimise extra config, I propose that the Kafka Spring client sets this property automatically, thus avoiding the need to set it via the "properties" map in the YML file or programmatically.

Spring Boot version: 2.1.9.RELEASE
Kafka version: 2.0.1

Example application.yml:
```
kafka:
  consumer:
    bootstrap-servers: <server>
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    ssl:
      truststore-location: <trust store location>
      truststore-password: <password>
    properties:
      security.protocol: SSL
```
